---
- name: Install Nginx and copy config files
  block:
    - name: Add nginx repository
      apt_repository:
        repo: "{{ nginx_ppa }}"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        force: yes
        update_cache: yes
      notify: Start Nginx

    - name: Template nginx.conf
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Template nginx-site.conf
      template:
        src: nginx-site.conf.j2
        dest: /etc/nginx/sites-available/{{ http_conf }}
      notify: Reload Nginx

    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent

    - name: "Add ssl keys"
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/private/
      with_fileglob: "ssl_certs/*.key"

    - name: "Add ssl pub keys"
      copy:
        src: "{{ item }}"
        dest: /etc/ssl/certs/
      with_fileglob: "ssl_certs/*.pem"

    - name: Enables new site
      file:
        src: /etc/nginx/sites-available/{{ http_conf }}
        dest: /etc/nginx/sites-enabled/{{ http_conf }}
        state: link
      notify: Restart Nginx

    - name: Permissions /var/log/nginx
      file:
        path: /var/log/nginx/
        mode: 0755
        recurse: yes